-- Direct-message feature =====================================================
-- Run this script in the Supabase SQL editor or include it in your migration
-- pipeline *after* the `profiles` table already exists.

--------------------------------------------------------------------------------
-- 1.  Table definition
--------------------------------------------------------------------------------
create table if not exists public.direct_messages (
  id            bigint generated by default as identity primary key,
  sender_id     uuid not null references public.profiles (id) on delete cascade,
  receiver_id   uuid not null references public.profiles (id) on delete cascade,
  content       text not null,
  created_at    timestamptz not null default now()
);

-- Helpful composite index for conversation look-ups
create index if not exists direct_messages_pair_idx
  on public.direct_messages (least(sender_id, receiver_id), greatest(sender_id, receiver_id), created_at desc);

--------------------------------------------------------------------------------
-- 2.  Enable Row-Level-Security (RLS)
--------------------------------------------------------------------------------
alter table public.direct_messages enable row level security;

--------------------------------------------------------------------------------
-- 3.  RLS policies
--------------------------------------------------------------------------------
-- Read:  Either the sender or the receiver can see the message
create policy "Can read own direct messages" on public.direct_messages
  for select
  using ( auth.uid() = sender_id or auth.uid() = receiver_id );

-- Insert:  Only the logged-in user may create a message where they are the sender
create policy "Sender can insert direct message" on public.direct_messages
  for insert
  with check ( auth.uid() = sender_id );

-- Delete:  Allow the sender to delete messages they sent (optional)
create policy "Sender can delete own direct message" on public.direct_messages
  for delete
  using ( auth.uid() = sender_id );

-- Updates are disallowed (immutable messages).  Remove this comment and add a
-- policy if you need to support message edits.

--------------------------------------------------------------------------------
-- 4.  Verify
--------------------------------------------------------------------------------
-- Example test (run as a privileged role):
-- select * from auth.uid(); -- should be NULL when run as service role
-- call auth.sign_in_as_user('some-sender-uuid');
-- insert into public.direct_messages (sender_id, receiver_id, content)
--   values ('some-sender-uuid', 'some-receiver-uuid', 'hello there');
-- select * from public.direct_messages where sender_id = 'some-sender-uuid';
-- call auth.sign_out();

-- End of file --------------------------------------------------------------- 